### ISSUE TITLE
Shader Completely White in Resolume OSX

### ISSUE THREAD

**Issue by DanielArnett** [leadedge/ShaderMaker#2]
I made a shader for Resolume that is working well on Windows. When I switch to osx the shader compiles properly but does not display properly in Resolume. The output becomes completely white. Even with the simplest shader I can possibly make

```
void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
        vec3 col = texture2D(iChannel0, fragCoord.xy / iResolution.xy);
        fragColor = vec4(col, 1.0);
}
```

I still only see a purely white screen.

**Comment by leadedge** [comment]
I can't really help to debug with OSX. Your simple example works fine for me on Windows as you say.  Maybe eliminate the texture and see if you get a red screen. Then you have a direction to follow.

fragColor = vec4(1.0, 0.0, 0.0, 1.0);

If you get a red screen OK it could be due to the texture type, perhaps texture2DRect.

**Comment by DanielArnett** [comment]
Yes setting fragcolor worked, however using texture2dRect made it go white
again. You're onto the issue though which is I can't access the "source"
texture, which my shader depends on. Other shaders which only generate
imagery work fine though.

**Comment by DanielArnett** [comment]
I believe the solution was that I needed .xyz after my texture2d().

**Comment by leadedge** [comment]
Yes you are right. But I would expect the shader compiler to fail in that case though. Strange that it works at all with Windows. I tested this exact code.

I also looked at your repository and found you were having trouble renaming the parameters. You can't do that without changing all the setup code for the uniforms, but you can rename what they appear as in SetParamInfo. 

To stop the ones you don't want coming up, disable their SetParamInfo lines and comment out the relevant code in GetParameterDisplay, GetFloatParameter and SetFloatParameter. That way you can make the plugin look like it was made to purpose.

I have done exactly this in the last couple of days and it works just fine. But to add add buttons and checkboxes you have to add support for the new uniforms and it starts to get time consuming.

My application is very similar. If you are interested then email me.

**Comment by brucelane** [comment]
It's funny yesterday I wanted to suggest to use fragColor = vec4(1.0, 0.0, 0.0, 1.0) !

**Comment by leadedge** [comment]
I don't know how many times I have needed to do that.

**Comment by DanielArnett** [comment]
@leadedge Thanks for looking up my project. Yeah the next thing I was going to ask was how to make an input. Is there a way I can set the values to be 50.0-150.0 instead of 0.0-1.0?

**Comment by DanielArnett** [comment]
@leadedge Alright I finally completed my first Shader and it works on both Windows and OSX in Resolume! Thank you so much for making this tool to help people like myself. 

A few things that OSX didn't like that worked fine in Windows:

* float2 & float3
* atan2()
* texture2d() without .xyz afterward
