### ISSUE TITLE
ShaderToy

### ISSUE THREAD

**Issue by royben** [leadedge/ShaderMaker#4]
Hi there,
Very nice project!

I successfully compiled and displayed all the ShaderToy included examples.
But I just can't make any other shader to work from the same website..

For example, here is my code:

```
float t (iGlobalTime * 0.25 + 10.0)

float hash(float n) { return fract(sin(n) * 1e4); }
float rand(vec2 n) {
	return fract(sin(dot(n, vec2(12.9898, 4.1414))) * 43758.5453);
}

const int nbMeta = 30;
vec3 meta[nbMeta];
float map(in vec2 p)
{
	float d = 0.0;
	for (int i = 0; i<nbMeta; i++)
	{
		d += meta[i].z / (length(p - meta[i].xy));
	}
	return d;
}

vec3 normal(in vec2 p)
{
	vec2 eps = vec2(0.1, 0.0);
	vec3 n;
	n.x = map(p) - map(p + eps.xy);
	n.y = eps.x * 2.0;
	n.z = map(p) - map(p + eps.yx);

	n = normalize(n);
	return n;
}


vec3 bckground(in vec2 uv)
{
	vec3 c = texture(iChannel0, vec2(uv.y / uv.x, t * 0.2 + uv.y * 0.05)).rgb;
	return pow(c, vec3(2.2)) + pow(c * 1.3, vec3(10.2));
}

vec3 bckground2(in vec2 uv)
{
	vec3 c = texture(iChannel1, vec2(uv.y / uv.x, t * 0.2 + uv.y * 0.05)).rgb;
	return pow(c, vec3(2.2)) + pow(c *1.3, vec3(10.2));
}

void mainImage(out vec4 fragColor, in vec2 fragCoord)
{
	vec2 q = fragCoord.xy / iResolution.xy;
	vec2 uv = fragCoord.xy / iResolution.xy * 2.0 - 1.0;
	uv.x *= iResolution.x / iResolution.y;
	vec3 col = vec3(0.0);


	for (int i = 0; i<nbMeta; i++)
	{
		meta[i].x = cos(t*hash(float(i)) * 2.0) * hash(float(i) + 0.1) * 2.0;
		meta[i].y = sin(t*hash(float(i))) * hash(float(i) + 0.2);
		meta[i].z = abs(hash(float(i))) * 5.0 + 0.01;
	}


	float d = map(uv);
	vec3 n = normal(uv);

	vec2 p = uv + n.rb;
	p = mix(uv, p, clamp(pow(q.x*q.y*(1.0 - q.x) * (1.0 - q.y) * 20.0, 2.5), 0.0, 1.0));
	col.r = bckground(p + vec2(0.01, 0.0)).r;
	col.g = bckground(p + vec2(0.0, 0.01)).g;
	col.b = bckground(p + vec2(0.0, 0.01)).b;
	col = pow(col, vec3(1.0 / 2.2));

	col = mix(bckground2(uv + vec2(0.0, 0.2)).rgb, col, clamp(pow(q.x*q.y*(1.0 - q.x)*(1.0 - q.y) * 30.0, 2.5), 0.0, 1.0));
	//

	col *= 0.5 + 0.5 * pow(q.x*q.y * (1.0 - q.x) * (1.0 - q.y) * 50.0, 0.5);

	fragColor = vec4(col, 1.0);
}
```

________________________________
And this is the original source:
https://www.shadertoy.com/view/MlSXWV

Can you please help me understand what I am doing wrong?

Thanks!

**Comment by brucelane** [comment]
try to replace:
void mainImage(out vec4 fragColor, in vec2 fragCoord) by void main(void)
fragColor by gl_FragColor
fragCoord by gl_FragCoord
At first sight, but I'm not sure, I can't test at the moment

**Comment by royben** [comment]
Thanks.

Actually the solution was:
float t(iGlobalTime*.25 + 10.); by float t = (iGlobalTime*.25 + 10.);

**Comment by brucelane** [comment]
ah ok I see... it was a #define t (iGlobalTime*.25+10.)

**Comment by royben** [comment]
OK last one (sorry for bugging, I am really excited about this..)

```
float tunnel(vec3 p)
{
	return cos(p.x) + cos(p.y*1.5) + cos(p.z) + cos(p.y*20.)*.05;
}

float ribbon(vec3 p)
{
	return length(max(abs(p - vec3(cos(p.z*1.5)*.3, -.5 + cos(p.z)*.2, .0)) - vec3(.125, .02, iGlobalTime + 3.), vec3(.0)));
}

float scene(vec3 p)
{
	return min(tunnel(p), ribbon(p));
}

vec3 getNormal(vec3 p)
{
	vec3 eps = vec3(.1, 0, 0);
	return normalize(vec3(scene(p + eps.xyy), scene(p + eps.yxy), scene(p + eps.yyx)));
}

void main(out vec4 fragColor, in vec2 fragCoord)
{
	vec2 v = -1.0 + 2.0 * fragCoord.xy / iResolution.xy;
	v.x *= iResolution.x / iResolution.y;

	vec4 color = vec4(0.0);
	vec3 org = vec3(sin(iGlobalTime)*.5, cos(iGlobalTime*.5)*.25 + .25, iGlobalTime);
	vec3 dir = normalize(vec3(v.x*1.6, v.y, 1.0));
	vec3 p = org, pp;
	float d = .0;

	//First raymarching
	for (int i = 0; i<64; i++)
	{
		d = scene(p);
		p += d*dir;
	}
	pp = p;
	float f = length(p - org)*0.02;

	//Second raymarching (reflection)
	dir = reflect(dir, getNormal(p));
	p += dir;
	for (int i = 0; i<32; i++)
	{
		d = scene(p);
		p += d*dir;
	}
	color = max(dot(getNormal(p), vec3(.1, .1, .0)), .0) + vec4(.3, cos(iGlobalTime*.5)*.5 + .5, sin(iGlobalTime*.5)*.5 + .5, 1.)*min(length(p - org)*.04, 1.);

	//Ribbon Color
	if (tunnel(pp)>ribbon(pp))
		color = mix(color, vec4(cos(iGlobalTime*.3)*.5 + .5, cos(iGlobalTime*.2)*.5 + .5, sin(iGlobalTime*.3)*.5 + .5, 1.), .3);

	//Final Color
	vec4 fcolor = ((color + vec4(f)) + (1. - min(pp.y + 1.9, 1.))*vec4(1., .8, .7, 1.))*min(iGlobalTime*.5, 1.);
	fragColor = vec4(fcolor.xyz, 1.0);
}
```

I suspect the line:
vec3 p = org, pp;

As you stated, the compiler does not like those commas, but what it the alternative here?

**Comment by brucelane** [comment]
try 
vec3 p = org;
vec3 pp;

**Comment by royben** [comment]
Applying your solution + void main(void) did it.

Thanks!

**Comment by royben** [comment]
Hi again,

There are many Shaders composed from several components working together, like "Buf A" and "Image"..
See:
https://www.shadertoy.com/view/llK3Dy

How should I tackle those in my code? They both seem to have "main void" functions.. And I don't really understand what is the relation between them.. Can you please guide me in some direction? Your help is greatly appreciated. Thanks.

**Comment by leadedge** [comment]
I am glad that Bruce has been able to help you with this.

The problem with # characters is with the Stringizing operator. You have to avoid them. This is explained in the code along with a link to the Microsoft documentation. Commas are also a problem although I have not documented that. 

Using Stringify makes it possible to copy/past the entire shader code in one block. Otherwise you have to include each line in quotes as you can see in the Freeframe "Heat" example. I have explored another way using resources to pick up the shader file which works well but I have not included it. I seem to recall that in the end it has the same limitations for # and commas.

After this project was completed, Shadertoy came out with the concept of buffers and multiple shader code. The idea is that the result from one is used in another and you can get feedback effects. Many people are using this now with impressive results.  The idea is similar to the ISF concept. I had a look at implementing this but it becomes a mess quickly without re-organising the entire code and starting again. I also had a look at ISF but similarly decided it would also need a re-write. Magic Music Visuals has a very nice ISF module if you want to explore them.

So the current code is limited to shaders with a single main function. There are lots of these though and I collect them as I get a moment. You will find that even some of the single function shaders don't work straight away. Debugging them is possible but can be difficult unless you understand the shader code.  Also you have to avoid any with audio, but this is generally easy to remove.

One way to test the function of a shader is to save it as a text file and load it with "ShaderLoader". The code is essentially the same, so you can debug by just modifying the text file. There are edit and reload functions in the ShaderLoader plugin to do just that.

You might also look at "ShaderToy Sender" which is a stand-alone shader loader program available to Spout supporters. I created this and generally use it for debugging shaders so that I don't have to start up a large host program.

**Comment by royben** [comment]
Hi Lynn,

Thank you for the detailed explanation. It made things much clearer to me.
Actually you are right, about the # character. Even if I don't use the Stringizing Operator it will still mess the FFGL plugin, I am not sure why. Maybe it is the OpenGL loader..

I have manage to squeeze out some nice shaders (with no buffers) from ShaderToy.
Then, I moved to this GLSL gallery:
http://glslsandbox.com/

There also, I managed to squeeze out some, but I think there is an issue with many of them which contains the line:
#extension GL_OES_standard_derivatives : enable

For example:
http://glslsandbox.com/e#39617.0

Do you have any suggestion about that? Have you managed to make them work?

Thanks,

**Comment by leadedge** [comment]
I looked this up and it requires OpenGL ES 2.0. It provides macros and the one used in this shader is fwidth. You will probably need to remove "precision mediump float;" as well.

Have a look at the ShaderToy equivalent https://www.shadertoy.com/view/XsByzm

I tested this and it works. This will show you the differences and you should be able to reproduce the changes he has made to get the red colour.

This works too :

https://www.shadertoy.com/view/ll3GRM 

I have added these to the collection.

**Comment by royben** [comment]
Managed to reproduce this nice one:
http://glslsandbox.com/e#39610.1

Using this code on ShaderToy:

```
uniform float time;
uniform vec2 mouse;
uniform vec2 resolution;

#define rsqrt inversesqrt
#define clamp(x) clamp(x, 0.0, 1.0)

const float Pi = 3.14159265359;

float InvLerp(float a, float b, float r) { return (a - r) / (a - b); }

float Pow4(float x)
{
    float x2 = x*x;
    
    return x2*x2;
}

float Root4(float x)
{
    return rsqrt(rsqrt(x));
}

float SinToGWave00(float x)
{
    return 1.0 - Root4(1.0 - x);
}

float SinToGWave0(float x, float s)
{
    float ss = 1.0 - Pow4(1.0 - s);
    
    return SinToGWave00(x * ss);
}

float SinToGWave0N(float x, float s)
{
    return SinToGWave0(x, s) / s;
}

float SinToGWave(float x, float s)
{
    return SinToGWave0(x * 0.5 + 0.5, s) * 2.0 - s;
}

float SinToGWaveN(float x, float s)
{
    return SinToGWave0(x * 0.5 + 0.5, s) / s * 2.0 - 1.0;
}

// inverse ground truth curve (can not be analytically inverted)
float InvGW(float y, float s)
{
    return acos(y/s) - sqrt(s*s - y*y);
}

float InvGW0(float y, float s)
{
    return InvGW((y * 2.0 - 1.0) * s, s) / Pi;
}
    

float Plot(float f, float y)
{
    float v = f - y;
    v /= length(vec2(dFdx(v), dFdy(v)));
    v = clamp(1.0 - abs(v));
    
    return v;
}

void mainImage( out vec4 fragColor, in vec2 uv )
{
    float Time = iGlobalTime;
    
    vec2 tex = uv / iResolution.xy;
    vec2 tex2 = tex * vec2(iResolution.x / iResolution.y, 1.0);
    
    float x = tex2.x;
    float xx1 = abs(mod(x - 1.0, 2.0) - 1.0);
    float xx2 = abs(mod(x + 1.5, 2.0) - 1.0);
    float y = tex2.y;
    
    vec3 col = vec3(0.0);
    float cos0 = cos((x - 1.5) * Pi);
    float cos1 = cos0/Pi*2.0 * 0.5 + 0.5;
    col = mix(col, vec3(0.05), Plot(0.5, y));
    col = mix(col, vec3(0.2), Plot(cos1, y));
    
    float s = 1.0;// amplitude scale of the curve; dictates the shape (s=1: cycloid | s=0: sine)
    s = mix(0.05, 0.95, sin(Time) * 0.5 + 0.5);

    float sp = 0.5 - 0.5 * s/Pi*2.0;// used for plotting the ground truth version

    // normalized to range [0..1]
    col = mix(col, vec3(1.0, 0.0, 0.0), Plot(InvGW0(y, s), xx1));// correct
    col = mix(col, vec3(1.0), Plot(SinToGWave0N(cos((x - 0.0) * Pi) * 0.5 + 0.5, s), y));// approx
    
    // unnormalized
    col = mix(col, vec3(0.0, 1.0, 0.0), Plot(InvGW0(InvLerp(sp, 1.0 - sp, y), s), xx2));// correct
    col = mix(col, vec3(1.0), Plot(SinToGWave(cos0, s)/Pi*2.0 * 0.5 + 0.5, y));// approx
   
    
    //col = vec3(v);
	//fragColor = vec4(tex2, 0.0,1.0);
    fragColor = vec4(pow(clamp(col), vec3(1.0/2.2)), 1.0);
}
```

It works, but in order to compile it, I need to somehow get rid of those two lines

```
#define rsqrt inversesqrt
#define clamp(x) clamp(x, 0.0, 1.0)
```

What is the alternative here, I am not sure..

Another topic..
The FFGL plugin exposes the same parameters on all plugins Time, MouseX etc..
I am interested in implementing a custom parameter that will modify a global value inside the shader, or maybe will be used directly by the shader. 
Is this possible? 

Thanks again!

**Comment by leadedge** [comment]
The # character is the problem again so you can't use #define. If you really need defines you can make functions instead, but in this case the define is just being lazy, so you can replace with the originals.
```
return inversesqrt(inversesqrt(x));
v = clamp((1.0 - abs(v)), 0.0, 1.0);
fragColor = vec4(pow(clamp(col, 0.0, 1.0), vec3(1.0/2.2)), 1.0);
```
Then it will work. Another one added to the collection!

Yes the code can be modified to include whatever parameters you want. But you will also need to set up the new uniforms for the shader.  That can be done too but you will need to think about it. Use the FFGL Heat example as a guide.

Otherwise you might be able to simply use existing parameters. I often use "inputColour" for floats. Then you can disable the parameters you don't want and rename them. Take care that you get the parameter numbering right - 0 to whatever.

This has a similar requirement, so you should be able to get some guide from that -

https://github.com/leadedge/ShaderLoader/issues/2

**Comment by royben** [comment]
Still not showing on host..

This is my code:

```
uniform float time;
uniform vec2 mouse;
uniform vec2 resolution;


const float Pi = 3.14159265359;

float InvLerp(float a, float b, float r) { return (a - r) / (a - b); }

float Pow4(float x)
{
	float x2 = x*x;

	return x2*x2;
}

float Root4(float x)
{
	return inversesqrt(inversesqrt(x));
}

float SinToGWave00(float x)
{
	return 1.0 - Root4(1.0 - x);
}

float SinToGWave0(float x, float s)
{
	float ss = 1.0 - Pow4(1.0 - s);

	return SinToGWave00(x * ss);
}

float SinToGWave0N(float x, float s)
{
	return SinToGWave0(x, s) / s;
}

float SinToGWave(float x, float s)
{
	return SinToGWave0(x * 0.5 + 0.5, s) * 2.0 - s;
}

float SinToGWaveN(float x, float s)
{
	return SinToGWave0(x * 0.5 + 0.5, s) / s * 2.0 - 1.0;
}

// inverse ground truth curve (can not be analytically inverted)
float InvGW(float y, float s)
{
	return acos(y / s) - sqrt(s*s - y*y);
}

float InvGW0(float y, float s)
{
	return InvGW((y * 2.0 - 1.0) * s, s) / Pi;
}


float Plot(float f, float y)
{
	float v = f - y;
	v /= length(vec2(dFdx(v), dFdy(v)));


	v = clamp((1.0 - abs(v)), 0.0, 1.0);

	return v;
}

void mainImage(out vec4 fragColor, in vec2 fragCoord)
{
	float Time = iGlobalTime;

	vec2 tex = fragCoord / iResolution.xy;
	vec2 tex2 = tex * vec2(iResolution.x / iResolution.y, 1.0);

	float x = tex2.x;
	float xx1 = abs(mod(x - 1.0, 2.0) - 1.0);
	float xx2 = abs(mod(x + 1.5, 2.0) - 1.0);
	float y = tex2.y;

	vec3 col = vec3(0.0);
	float cos0 = cos((x - 1.5) * Pi);
	float cos1 = cos0 / Pi*2.0 * 0.5 + 0.5;
	col = mix(col, vec3(0.05), Plot(0.5, y));
	col = mix(col, vec3(0.2), Plot(cos1, y));

	float s = 1.0;// amplitude scale of the curve; dictates the shape (s=1: cycloid | s=0: sine)
	s = mix(0.05, 0.95, sin(Time) * 0.5 + 0.5);

	float sp = 0.5 - 0.5 * s / Pi*2.0;// used for plotting the ground truth version

									  // normalized to range [0..1]
	col = mix(col, vec3(1.0, 0.0, 0.0), Plot(InvGW0(y, s), xx1));// correct
	col = mix(col, vec3(1.0), Plot(SinToGWave0N(cos((x - 0.0) * Pi) * 0.5 + 0.5, s), y));// approx

																						 // unnormalized
	col = mix(col, vec3(0.0, 1.0, 0.0), Plot(InvGW0(InvLerp(sp, 1.0 - sp, y), s), xx2));// correct
	col = mix(col, vec3(1.0), Plot(SinToGWave(cos0, s) / Pi*2.0 * 0.5 + 0.5, y));// approx


																				 //col = vec3(v);
																				 //fragColor = vec4(tex2, 0.0,1.0);
	fragColor = vec4(pow(clamp(col, 0.0, 1.0), vec3(1.0 / 2.2)), 1.0);
}
```

Have you managed to display this shader on FFGL host?

**Comment by royben** [comment]
BTW:

I have managed to rename the "Red" component name and modify a GLSL shader values using it 👍

**Comment by leadedge** [comment]
Remove the uniform declarations at the top -
```
uniform float time;
uniform vec2 mouse;
uniform vec2 resolution;
```
If you include these, the shader is assumed to be GLSLSandbox rather than Shadertoy. Later in the code there is reference to "iGlobalTime" etc. which are Shadertoy uniforms. If you don't include any uniform declarations at all, the shader is assumed to be Shadertoy.

**Comment by royben** [comment]
Thanks Lynn,

I am struggling with a different issue:
Is it possible that all shaders produced with ShaderMaker delivers frames with a black background instead of transparent ?

When I use "Native" FFGL plugins I get a transparent background..

This is a test using an FFGL host from the FFGL SDK:

This is the standard FFGL plugin I found online:
![image](https://cloud.githubusercontent.com/assets/1214312/24842069/7ea72f0a-1d9a-11e7-935e-c818ea0b00e0.png)
And this is a shader produced by ShaderMaker:
![image](https://cloud.githubusercontent.com/assets/1214312/24842078/a265bee8-1d9a-11e7-955d-14507bd76121.png)

As you can see, there is no alpha channel.

I have read something about enabling the alpha channel on OpenGL:
```
	glEnable(GL_BLEND);
	glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
```

I tried to apply those settings on several places but with no success.

Your help is greatly appreciated. Thanks!

**Comment by leadedge** [comment]
That's entirely possible although an alpha value is generated by the shader.

Try a simple shader with "inputColour" and adjust the values to see the effect of adjusting alpha.
```
void main(void) {
    gl_FragColor = vec4(inputColour.r, inputColour.g, inputColour.b, inputColour.a);
}
```
To say any more I would need to investigate thoroughly and I don't have the time at the moment.

**Comment by royben** [comment]
Hi Lynn, 

I have tried to make this work per your suggestion without much success..
In the hope you can make some time for this..

In the meantime I have posted a job on Upwork, seeking for someone who can fix the issue with the alpha channel. Of course you are the preferable person for this, so let me know if you are interested..

Thanks!

**Comment by leadedge** [comment]
Change the plugin from FF_EFFECT to FF_SOURCE. I think you will find it will work then.

I tried your previous shader with -

`fragColor = vec4(pow(clamp(col, 0.0, 1.0), vec3(1.0 / 2.2)), inputColour.a);`

and it seems to work as expected when the alpha is adjusted.

I am not sure that a contractor would be cost-effective unless they are skilled with Freeframe in the first place. Please email me for more detail.
